http:
  build: ./http/
  ports:
   - "80:80"
   - "443:443"
  links:
   - jira
   - stash
   - bamboo

jira:
  build: ./jira/
  links:
   - db
  ports:
   - "8080:8080"
  volumes_from:
   - data

stash:
  build: ./stash/
  links:
   - db
  ports:
   - "7999:7999"
   - "7990:7990"
  volumes_from:
   - data

bamboo:
  build: ./bamboo/
  links:
   - db
  ports:
   - "8085:8085"
  volumes_from:
   - data

db:
  build: ./db/
  environment:
    POSTGRES_USER: atlassian
    POSTGRES_PASSWORD: atlassian
  expose:
    - "5432"
  volumes_from:
    - data

data:
    image: busybox
    volumes:
        - /var/atlassian
        - /var/lib/postgresql/data
